---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: pacman-secret
  namespace: pacman
spec:
  encryptedData:
    pass: AgCCQwVncETFACMOpxStXyKc2K6u6yq6Xaubo+wsrTJrnPX2AMPfxdd1EU/UIXZQS8NTAvLMQjsQXsWmqSQpBHYi+RMIciV6DnkNXmlVRTJ7jPeHSruL2Dipo6q5SNxD7g6svYhV3pDp1WBmKjHE5+ZmrNJVI3vWh+tdvvuKR7ji80FoAYD9/sCF2ry6MbngJs7B9N7yTsqfDK+YDGWrywpmhoeLhciGQuV/Q9HMu3cNbNnTpiRHFo9TtgWD86a5M9m9dSQAn+PGVg9vCDPWT+Ff/GHse2CGYHX0eCSXGQeDPOEodGkNFlK2PLDL0ZvQXCof7V0U9tBBPatpqIOof6+DMZOH3g2gE8PDelEUkspaMvYuNt0rBNi9CN/NSLzF0RdNPH3GMlxlL8Owq/e5F4/nJTEL4s+u3R/4RXMSL6lHyztH8IAqWzAB9Rfxk2XdueCKWKgdl4I3qG8OdnANbZp1/BC4TaT9yDv2wh0Cjau8xUMp/Ynw6LgQrO7q9wHPilzuhgV6VOsQSEXzpq1lzjh2xPB2JNk6lgUj/34pZcbAVsrVnPiuOGJlPuSmiZsTpkGQhLfuPDI69fSsTXBTm0hccXNW96XhBQ0b9IyNsq3thkuIYuoW+DH4PMzAByQdQPmRUCRzzXvavCRZGKaWnxkFqPrzc8ND9Cn/zCOncc2ypdjxeKaF/viMpshlGbk6BzRG49MQ/4U=
    user: AgCux8zpIu6ybTiWmF+/4HWGg41MIv7U7waysqlt2uQ+M0SfmCIVRVYNr2Eb6njwyqFBj0KeW9LHMI6mXyD/61lh9TNLpv/GunF+NyYvRUamMtNaIk2TecynvKHtd3fB1EjuqqaLceo5dUzEnnok88hLWkPKhkuq/94nFdZohbHHpHmTyR+nscny7AK3AfcYMgiKOykHP0FrYTD+/iyKiaWGk/we2cnWsiP5JmZw1Takc7P3RcSnLt1r9UlnCW6JJH+3oqEYROcU9LQVW+FuEyL+Ultaf48kj3eXg36Ag9+j5UEM6GT88nGeqf42fIt0GtU6iq/Wcr8PQFEeWtPfzYivY/SHQn/olM6jAiryR9uxO/s7P+hFKH7E7yein8ItMx9p5Yeq6CDwalB9Lg9eOFXHtdkkIbv0DdFz80vJua27U7wYNoqwtmzy8hErqcoFwxKAIJGjaYFcWSTN7x8ZVz0sk2DVCJY40SDI2tjh0u7AHW2bfw1BPjTu9HuGE+8ZrItDod5qEIJWyGgio2N3qWmDA0bcIYlXmYlon6ealZscQvAX0PpS3aea3wPBdqgRWql6Nd5GfnA2z2YMBaGPHrQyx1xXJtWy7vUEVC5dwUSsBsO+TxxKiLRuOGx/viOyuIQTtaTkrfoJFurrhJPc3hC1ki9KqTf1mISJBLi0zZhTuC/kYnSOeBaobQ/3TNZPsuD+1LWYNx4=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: pacman-secret
      namespace: pacman
    type: Opaque
